### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by aksj98**
Added comments to DS 1-4

### CODE REVIEW

**Comment by rishabhlakhotia** [comment]
Can you use `//` instead of `/*   */` for single line comments. It will give uniformity over the manual.

**Comment by aksj98** [comment]
Here is a good reason I am using `/* */` instead of `//` , here is the [official Microsoft website](https://msdn.microsoft.com/en-us/library/wfwda74e.aspx) stating why:
 
> The Microsoft compiler also supports single-line comments preceded by two forward slashes (//). If you compile with /Za (ANSI standard), these comments generate errors. These comments cannot extend to a second line.

if you still want me to use //, please comment here, though, I can change all the others to /* */ too. 
Cheers!

**Comment by rishabhlakhotia** [comment]
Let it be `//` for single line comments. Most people use Turbo C or codeblocks and that works fine in both. Moreover, this will prevent any confusion.

**Comment by aksj98** [comment]
Added `//` instead of `/* */` in all 4 files which are commented until now,
Cheers

**Comment by rishabhlakhotia** [comment]
Just merged it. Thanks :)

**Pull request merged**
